// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAflLTT61JklfEpHszIAKDEi-Kr-8pav5Q',
    appId: '1:180166017331:web:72658032dab4bf67bf7e46',
    messagingSenderId: '180166017331',
    projectId: 'ayni-tesis',
    authDomain: 'ayni-tesis.firebaseapp.com',
    storageBucket: 'ayni-tesis.firebasestorage.app',
    measurementId: 'G-R32ZF3ELMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIbShDnLBjPU9uZw-9Vi0HBiEf5WYMc4w',
    appId: '1:180166017331:android:d61b62c1724c1fdebf7e46',
    messagingSenderId: '180166017331',
    projectId: 'ayni-tesis',
    storageBucket: 'ayni-tesis.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByCcD_18PC-oAZrtkfBckjfSd_CYy0AYs',
    appId: '1:180166017331:ios:300bfe51bd1315e0bf7e46',
    messagingSenderId: '180166017331',
    projectId: 'ayni-tesis',
    storageBucket: 'ayni-tesis.firebasestorage.app',
    iosBundleId: 'com.example.ayniApp',
  );
}
